export * from './responsibilityPoints'
export * from './createResponsibilityPoints'
export * from './updateResponsibilityPoints'
export * from './findResponsibilityPointsByCourse'
export * from './findResponsibilityPointsByStudentId'
