export const twelveAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
]

export const twelveCohortAssignedSeats = [
  { deskNumber: 1, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 2, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 3, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 4, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 5, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 6, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 7, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 8, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 9, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 10, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 11, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 12, redCohortStudent: null, whiteCohortStudent: null },
]

export const twentyFourAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
  { deskNumber: 13, student: null },
  { deskNumber: 14, student: null },
  { deskNumber: 15, student: null },
  { deskNumber: 16, student: null },
  { deskNumber: 17, student: null },
  { deskNumber: 18, student: null },
  { deskNumber: 19, student: null },
  { deskNumber: 20, student: null },
  { deskNumber: 21, student: null },
  { deskNumber: 22, student: null },
  { deskNumber: 23, student: null },
  { deskNumber: 24, student: null },
]

export const twentyFourCohortAssignedSeats = [
  { deskNumber: 1, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 2, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 3, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 4, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 5, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 6, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 7, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 8, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 9, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 10, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 11, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 12, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 13, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 14, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 15, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 16, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 17, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 18, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 19, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 20, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 21, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 22, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 23, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 24, redCohortStudent: null, whiteCohortStudent: null },
]

export const thirtyAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
  { deskNumber: 13, student: null },
  { deskNumber: 14, student: null },
  { deskNumber: 15, student: null },
  { deskNumber: 16, student: null },
  { deskNumber: 17, student: null },
  { deskNumber: 18, student: null },
  { deskNumber: 19, student: null },
  { deskNumber: 20, student: null },
  { deskNumber: 21, student: null },
  { deskNumber: 22, student: null },
  { deskNumber: 23, student: null },
  { deskNumber: 24, student: null },
  { deskNumber: 25, student: null },
  { deskNumber: 26, student: null },
  { deskNumber: 27, student: null },
  { deskNumber: 28, student: null },
  { deskNumber: 29, student: null },
  { deskNumber: 30, student: null },
]

export const thirtyCohortAssignedSeats = [
  { deskNumber: 1, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 2, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 3, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 4, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 5, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 6, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 7, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 8, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 9, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 10, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 11, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 12, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 13, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 14, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 15, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 16, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 17, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 18, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 19, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 20, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 21, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 22, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 23, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 24, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 25, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 26, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 27, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 28, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 29, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 30, redCohortStudent: null, whiteCohortStudent: null },
]

export const thirtySixAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
  { deskNumber: 13, student: null },
  { deskNumber: 14, student: null },
  { deskNumber: 15, student: null },
  { deskNumber: 16, student: null },
  { deskNumber: 17, student: null },
  { deskNumber: 18, student: null },
  { deskNumber: 19, student: null },
  { deskNumber: 20, student: null },
  { deskNumber: 21, student: null },
  { deskNumber: 22, student: null },
  { deskNumber: 23, student: null },
  { deskNumber: 24, student: null },
  { deskNumber: 25, student: null },
  { deskNumber: 26, student: null },
  { deskNumber: 27, student: null },
  { deskNumber: 28, student: null },
  { deskNumber: 29, student: null },
  { deskNumber: 30, student: null },
  { deskNumber: 31, student: null },
  { deskNumber: 32, student: null },
  { deskNumber: 33, student: null },
  { deskNumber: 34, student: null },
  { deskNumber: 35, student: null },
  { deskNumber: 36, student: null },
]

export const thirtySixCohortAssignedSeats = [
  { deskNumber: 1, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 2, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 3, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 4, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 5, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 6, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 7, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 8, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 9, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 10, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 11, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 12, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 13, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 14, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 15, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 16, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 17, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 18, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 19, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 20, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 21, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 22, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 23, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 24, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 25, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 26, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 27, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 28, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 29, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 30, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 31, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 32, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 33, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 34, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 35, redCohortStudent: null, whiteCohortStudent: null },
  { deskNumber: 36, redCohortStudent: null, whiteCohortStudent: null },
]
// export const initialSeatAssigner =(maxSeats: number)=> {

//     initialSeatAssigner()

// }
