export const twelveAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
]

export const twentyFourAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
  { deskNumber: 13, student: null },
  { deskNumber: 14, student: null },
  { deskNumber: 15, student: null },
  { deskNumber: 16, student: null },
  { deskNumber: 17, student: null },
  { deskNumber: 18, student: null },
  { deskNumber: 19, student: null },
  { deskNumber: 20, student: null },
  { deskNumber: 21, student: null },
  { deskNumber: 22, student: null },
  { deskNumber: 23, student: null },
  { deskNumber: 24, student: null },
]

export const thirtyAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
  { deskNumber: 13, student: null },
  { deskNumber: 14, student: null },
  { deskNumber: 15, student: null },
  { deskNumber: 16, student: null },
  { deskNumber: 17, student: null },
  { deskNumber: 18, student: null },
  { deskNumber: 19, student: null },
  { deskNumber: 20, student: null },
  { deskNumber: 21, student: null },
  { deskNumber: 22, student: null },
  { deskNumber: 23, student: null },
  { deskNumber: 24, student: null },
  { deskNumber: 25, student: null },
  { deskNumber: 26, student: null },
  { deskNumber: 27, student: null },
  { deskNumber: 28, student: null },
  { deskNumber: 29, student: null },
  { deskNumber: 30, student: null },
]

export const thirtySixAssignedSeats = [
  { deskNumber: 1, student: null },
  { deskNumber: 2, student: null },
  { deskNumber: 3, student: null },
  { deskNumber: 4, student: null },
  { deskNumber: 5, student: null },
  { deskNumber: 6, student: null },
  { deskNumber: 7, student: null },
  { deskNumber: 8, student: null },
  { deskNumber: 9, student: null },
  { deskNumber: 10, student: null },
  { deskNumber: 11, student: null },
  { deskNumber: 12, student: null },
  { deskNumber: 13, student: null },
  { deskNumber: 14, student: null },
  { deskNumber: 15, student: null },
  { deskNumber: 16, student: null },
  { deskNumber: 17, student: null },
  { deskNumber: 18, student: null },
  { deskNumber: 19, student: null },
  { deskNumber: 20, student: null },
  { deskNumber: 21, student: null },
  { deskNumber: 22, student: null },
  { deskNumber: 23, student: null },
  { deskNumber: 24, student: null },
  { deskNumber: 25, student: null },
  { deskNumber: 26, student: null },
  { deskNumber: 27, student: null },
  { deskNumber: 28, student: null },
  { deskNumber: 29, student: null },
  { deskNumber: 30, student: null },
  { deskNumber: 31, student: null },
  { deskNumber: 32, student: null },
  { deskNumber: 33, student: null },
  { deskNumber: 34, student: null },
  { deskNumber: 35, student: null },
  { deskNumber: 36, student: null },
]
// export const initialSeatAssigner =(maxSeats: number)=> {

//     initialSeatAssigner()

// }
