/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as t from "./typeDefs"
import { core } from "@nexus/schema"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "Date";
    time<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "Time";
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "DateTime";
    JSON<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "JSON";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    time<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Time";
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    JSON<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSON";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AddNewChapterInput: { // input type
    chapterNumber: number; // Int!
    chapterTitle: string; // String!
    textTitle: string; // String!
  }
  AddNewTextInput: { // input type
    textTitle: string; // String!
  }
  AddStudentsToCourseInput: { // input type
    course: string; // String!
    studentUserName: string; // String!
  }
  AddVocabWordInput: { // input type
    _id: string; // ID!
    definition: string; // String!
    position: number; // Int!
    word: string; // String!
  }
  AssignEssayInput: { // input type
    assignedCourse: string; // String!
    dueDate: any; // Date!
    hasAssigner: string; // String!
    markingPeriod: NexusGenEnums['MarkingPeriodEnum']; // MarkingPeriodEnum!
    maxPoints: number; // Int!
    readings: NexusGenInputs['ReadingsInput']; // ReadingsInput!
    topic: NexusGenInputs['TopicInput']; // TopicInput!
  }
  ChangeVocabWordInput: { // input type
    _id: string; // ID!
    definition: string; // String!
    newDefinition: string; // String!
    newWord: string; // String!
    word: string; // String!
  }
  CreateCourseInput: { // input type
    period: string; // String!
    taughtBy: string; // String!
  }
  CreateTextSectionInput: { // input type
    fromChapterId: string; // String!
    hasProtocols: NexusGenInputs['TextSectionProtocolsInput'][]; // [TextSectionProtocolsInput!]!
    hasQuestions: NexusGenInputs['TextSectionQuestionsInput'][]; // [TextSectionQuestionsInput!]!
    hasVocab: NexusGenInputs['TextSectionVocabInput'][]; // [TextSectionVocabInput!]!
    header: string; // String!
    pageNumbers: NexusGenInputs['PageNumbersInput']; // PageNumbersInput!
  }
  FindAssignmentsToGradeInput: { // input type
    teacherUserName: string; // String!
  }
  FindChapterTitleInput: { // input type
    chapter_id: string; // ID!
  }
  FindChaptersInTextInput: { // input type
    textTitle: string; // String!
  }
  FindEssayByIdInput: { // input type
    _id: string; // ID!
  }
  FindEssaysByUserNameAndMarkingPeriodInput: { // input type
    markingPeriod: NexusGenEnums['MarkingPeriodEnum']; // MarkingPeriodEnum!
    userName: string; // String!
  }
  FindTextByTitleInput: { // input type
    title?: string | null; // String
  }
  FindTextSectionByIdInput: { // input type
    _id: string; // ID!
  }
  FindTextSectionsByChapterInput: { // input type
    fromChapter: string; // String!
    fromText: string; // String!
  }
  HasAssigner: { // input type
    assignerUserName?: string | null; // String
  }
  HasOwnerInput: { // input type
    ownerUserName?: string | null; // String
  }
  LoginInput: { // input type
    password: string; // String!
    userName: string; // String!
  }
  PageNumbersInput: { // input type
    endingPage: number; // Int!
    startingPage: number; // Int!
  }
  ReadingsInput: { // input type
    readingPages: string; // String!
    readingSections: string; // String!
  }
  RemoveTextSectionInput: { // input type
    _id: string; // ID!
  }
  ReturnGradedEssayInput: { // input type
    _id: string; // ID!
    comments: string[]; // [String!]!
    gradedDraft: any; // JSON!
    score: number; // Int!
  }
  StudentRegistrationInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    userName: string; // String!
  }
  SubmitEssayFinalDraftInput: { // input type
    _id: string; // ID!
    late: boolean; // Boolean!
    submittedFinalDraft: NexusGenInputs['SubmittedFinalDraftsInput']; // SubmittedFinalDraftsInput!
  }
  SubmittedFinalDraftsInput: { // input type
    comments: string[]; // [String!]!
    draft: any; // JSON!
    gradingDraft: any; // JSON!
    score: number; // Int!
  }
  TeacherRegistrationInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    title: NexusGenEnums['TitleEnum']; // TitleEnum!
    userName: string; // String!
  }
  TextChapterInput: { // input type
    chapterNumber: number; // Int!
    chapterTitle: string; // String!
  }
  TextInput: { // input type
    chapters: string[]; // [String!]!
    textTitle: string; // String!
  }
  TextSectionProtocolsInput: { // input type
    academicOutcomeTypes: NexusGenEnums['AcademicOutomeTypes']; // AcademicOutomeTypes!
    activityType: NexusGenEnums['ProtocolActivityTypes']; // ProtocolActivityTypes!
    task: string; // String!
  }
  TextSectionQuestionsInput: { // input type
    question: string; // String!
    questionType: NexusGenEnums['QuestionTypeEnum']; // QuestionTypeEnum!
  }
  TextSectionVocabInput: { // input type
    definition: string; // String!
    word: string; // String!
  }
  TopicInput: { // input type
    question: string; // String!
    questionType: NexusGenEnums['QuestionTypeEnum']; // QuestionTypeEnum!
  }
  UpdateTextSectionInput: { // input type
    _id: string; // ID!
    fromChapterId?: string | null; // String
    hasProtocols: NexusGenInputs['TextSectionProtocolsInput'][]; // [TextSectionProtocolsInput!]!
    hasQuestions: NexusGenInputs['TextSectionQuestionsInput'][]; // [TextSectionQuestionsInput!]!
    hasVocab: NexusGenInputs['TextSectionVocabInput'][]; // [TextSectionVocabInput!]!
    header: string; // String!
    pageNumbers: NexusGenInputs['PageNumbersInput']; // PageNumbersInput!
  }
  UpdateWorkingDraftInput: { // input type
    _id: string; // ID!
    updatedDraft: any; // JSON!
  }
}

export interface NexusGenEnums {
  AcademicOutomeTypes: "LOGIC_BUILDING" | "SCHEMA_BUIDING" | "SOCRATIC_QUESTIONS"
  MarkingPeriodEnum: "FIRST" | "FOURTH" | "SECOND" | "THIRD"
  ProtocolActivityTypes: "THINK_PAIR_SHARE"
  QuestionTypeEnum: "HOW_CAUSE_EFFECT" | "HOW_PROBLEM_SOLUTION" | "WHY_CAUSE_EFFECT"
  TitleEnum: "MISS" | "MR" | "MRS" | "MS"
}

export interface NexusGenRootTypes {
  AddNewChapterPayload: { // root type
    chapter: NexusGenRootTypes['Chapter']; // Chapter!
  }
  AddNewTextPayload: { // root type
    text: NexusGenRootTypes['Text']; // Text!
  }
  AddStudentsToCoursePayload: { // root type
    course: NexusGenRootTypes['Course']; // Course!
  }
  AddVocabWordPayload: { // root type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  AssignEssayPayload: { // root type
    essay: NexusGenRootTypes['Essay'][]; // [Essay!]!
  }
  Chapter: { // root type
    _id?: string | null; // ID
    chapterNumber: number; // Int!
    chapterTitle: string; // String!
    fromText: NexusGenRootTypes['Text']; // Text!
  }
  Course: { // root type
    _id?: string | null; // ID
    hasStudents: NexusGenRootTypes['Student'][]; // [Student!]!
    hasTeacher: NexusGenRootTypes['Teacher']; // Teacher!
    period: string; // String!
  }
  CreateCoursePayload: { // root type
    course: NexusGenRootTypes['Course']; // Course!
  }
  CreateTextSectionPayload: { // root type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  Essay: { // root type
    _id?: string | null; // ID
    assignedDate: any; // Date!
    dueDate: any; // Date!
    exempt: boolean; // Boolean!
    finalDraft?: NexusGenRootTypes['FinalDraftContainer'] | null; // FinalDraftContainer
    hasAssigner: NexusGenRootTypes['Teacher']; // Teacher!
    hasOwner: NexusGenRootTypes['Student']; // Student!
    late: boolean; // Boolean!
    markingPeriod: string; // String!
    readings: NexusGenRootTypes['Readings']; // Readings!
    score: NexusGenRootTypes['Score']; // Score!
    topic: NexusGenRootTypes['Topic']; // Topic!
    workingDraft: NexusGenRootTypes['WorkingDraft']; // WorkingDraft!
  }
  FinalDraftContainer: { // root type
    returned: boolean; // Boolean!
    submitted: boolean; // Boolean!
    submittedFinalDraft: NexusGenRootTypes['SubmittedFinalDraft']; // SubmittedFinalDraft!
    submitTime?: any | null; // DateTime
  }
  FindAssignmentsToGradePayload: { // root type
    assignments: NexusGenRootTypes['Assignment'][]; // [Assignment!]!
  }
  FindChapterTitlePayload: { // root type
    chapter: NexusGenRootTypes['Chapter']; // Chapter!
  }
  FindChaptersInTextPayload: { // root type
    chapters: NexusGenRootTypes['Chapter'][]; // [Chapter!]!
  }
  FindEssayByIdPayload: { // root type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  FindEssaysByUserNameAndMarkingPeriodPayload: { // root type
    essay?: NexusGenRootTypes['Essay'][] | null; // [Essay!]
  }
  FindTextByTitlePayload: { // root type
    text: NexusGenRootTypes['Text']; // Text!
  }
  FindTextSectionByIdPayload: { // root type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  FindTextSectionsByChapterPayload: { // root type
    textSections: NexusGenRootTypes['TextSection'][]; // [TextSection!]!
  }
  FindTextsPayload: { // root type
    texts: NexusGenRootTypes['Text'][]; // [Text!]!
  }
  LoginPayload: { // root type
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: {};
  PageNumbers: { // root type
    endingPage: number; // Int!
    startingPage: number; // Int!
  }
  Query: {};
  Reading_Guide: { // root type
    _id?: string | null; // ID
    assignedDate: any; // Date!
    completion: string; // String!
    dueDate: any; // Date!
    exempt: boolean; // Boolean!
    hasAssigner: NexusGenRootTypes['Teacher']; // Teacher!
    hasOwner: NexusGenRootTypes['Student']; // Student!
    late: boolean; // Boolean!
    markingPeriod: string; // String!
    readings: NexusGenRootTypes['Readings']; // Readings!
    score: NexusGenRootTypes['Score']; // Score!
  }
  Readings: { // root type
    readingPages: string; // String!
    readingSections: string; // String!
  }
  RemoveTextSectionPayload: { // root type
    removed: boolean; // Boolean!
  }
  ReturnGradedEssayPayload: { // root type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  Score: { // root type
    earnedPoints: number; // Int!
    maxPoints: number; // Int!
  }
  Student: { // root type
    _id?: string | null; // ID
    email?: string | null; // String
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    userName: string; // String!
  }
  StudentRegistrationPayload: { // root type
    student: NexusGenRootTypes['Student']; // Student!
  }
  SubmitEssayFinalDraftPayload: { // root type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  SubmittedFinalDraft: { // root type
    comments: string[]; // [String!]!
    draft: any; // JSON!
    gradingDraft: any; // JSON!
    score: number; // Int!
  }
  Teacher: { // root type
    _id?: string | null; // ID
    email?: string | null; // String
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    title: NexusGenEnums['TitleEnum']; // TitleEnum!
    userName: string; // String!
  }
  TeacherRegistrationPayload: { // root type
    teacher: NexusGenRootTypes['Teacher']; // Teacher!
  }
  Test: { // root type
    _id?: string | null; // ID
    assignedDate: any; // Date!
    dueDate: any; // Date!
    exempt: boolean; // Boolean!
    hasAssigner: NexusGenRootTypes['Teacher']; // Teacher!
    hasOwner: NexusGenRootTypes['Student']; // Student!
    late: boolean; // Boolean!
    markingPeriod: string; // String!
    readings: NexusGenRootTypes['Readings']; // Readings!
    score: NexusGenRootTypes['Score']; // Score!
    testName: string; // String!
  }
  Text: { // root type
    _id?: string | null; // ID
    textTitle: string; // String!
  }
  TextSection: { // root type
    _id?: string | null; // ID
    fromChapter: NexusGenRootTypes['Chapter']; // Chapter!
    hasProtocols: NexusGenRootTypes['TextSectionProtocols'][]; // [TextSectionProtocols!]!
    hasQuestions: NexusGenRootTypes['TextSectionQuestions'][]; // [TextSectionQuestions!]!
    hasVocab: NexusGenRootTypes['TextSectionVocab'][]; // [TextSectionVocab!]!
    header: string; // String!
    pageNumbers: NexusGenRootTypes['PageNumbers']; // PageNumbers!
  }
  TextSectionProtocols: { // root type
    academicOutcomeTypes: NexusGenEnums['AcademicOutomeTypes']; // AcademicOutomeTypes!
    activityType: NexusGenEnums['ProtocolActivityTypes']; // ProtocolActivityTypes!
    task: string; // String!
  }
  TextSectionQuestions: { // root type
    question: string; // String!
    questionType: NexusGenEnums['QuestionTypeEnum']; // QuestionTypeEnum!
  }
  TextSectionVocab: { // root type
    definition: string; // String!
    word: string; // String!
  }
  Topic: { // root type
    question: string; // String!
    questionType: NexusGenEnums['QuestionTypeEnum']; // QuestionTypeEnum!
  }
  UpdateTextSectionPayload: { // root type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  UpdateVocabPayload: { // root type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  UpdateWorkingDraftPayload: { // root type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  WorkingDraft: { // root type
    draft: any; // JSON!
  }
  Assignment: NexusGenRootTypes['Essay'] | NexusGenRootTypes['Reading_Guide'] | NexusGenRootTypes['Test'];
  User: NexusGenRootTypes['Student'] | NexusGenRootTypes['Teacher'];
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  Date: Date;
  DateTime: DateTime;
  JSON: JSON;
  Time: Time;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  AddNewChapterInput: NexusGenInputs['AddNewChapterInput'];
  AddNewTextInput: NexusGenInputs['AddNewTextInput'];
  AddStudentsToCourseInput: NexusGenInputs['AddStudentsToCourseInput'];
  AddVocabWordInput: NexusGenInputs['AddVocabWordInput'];
  AssignEssayInput: NexusGenInputs['AssignEssayInput'];
  ChangeVocabWordInput: NexusGenInputs['ChangeVocabWordInput'];
  CreateCourseInput: NexusGenInputs['CreateCourseInput'];
  CreateTextSectionInput: NexusGenInputs['CreateTextSectionInput'];
  FindAssignmentsToGradeInput: NexusGenInputs['FindAssignmentsToGradeInput'];
  FindChapterTitleInput: NexusGenInputs['FindChapterTitleInput'];
  FindChaptersInTextInput: NexusGenInputs['FindChaptersInTextInput'];
  FindEssayByIdInput: NexusGenInputs['FindEssayByIdInput'];
  FindEssaysByUserNameAndMarkingPeriodInput: NexusGenInputs['FindEssaysByUserNameAndMarkingPeriodInput'];
  FindTextByTitleInput: NexusGenInputs['FindTextByTitleInput'];
  FindTextSectionByIdInput: NexusGenInputs['FindTextSectionByIdInput'];
  FindTextSectionsByChapterInput: NexusGenInputs['FindTextSectionsByChapterInput'];
  HasAssigner: NexusGenInputs['HasAssigner'];
  HasOwnerInput: NexusGenInputs['HasOwnerInput'];
  LoginInput: NexusGenInputs['LoginInput'];
  PageNumbersInput: NexusGenInputs['PageNumbersInput'];
  ReadingsInput: NexusGenInputs['ReadingsInput'];
  RemoveTextSectionInput: NexusGenInputs['RemoveTextSectionInput'];
  ReturnGradedEssayInput: NexusGenInputs['ReturnGradedEssayInput'];
  StudentRegistrationInput: NexusGenInputs['StudentRegistrationInput'];
  SubmitEssayFinalDraftInput: NexusGenInputs['SubmitEssayFinalDraftInput'];
  SubmittedFinalDraftsInput: NexusGenInputs['SubmittedFinalDraftsInput'];
  TeacherRegistrationInput: NexusGenInputs['TeacherRegistrationInput'];
  TextChapterInput: NexusGenInputs['TextChapterInput'];
  TextInput: NexusGenInputs['TextInput'];
  TextSectionProtocolsInput: NexusGenInputs['TextSectionProtocolsInput'];
  TextSectionQuestionsInput: NexusGenInputs['TextSectionQuestionsInput'];
  TextSectionVocabInput: NexusGenInputs['TextSectionVocabInput'];
  TopicInput: NexusGenInputs['TopicInput'];
  UpdateTextSectionInput: NexusGenInputs['UpdateTextSectionInput'];
  UpdateWorkingDraftInput: NexusGenInputs['UpdateWorkingDraftInput'];
  AcademicOutomeTypes: NexusGenEnums['AcademicOutomeTypes'];
  MarkingPeriodEnum: NexusGenEnums['MarkingPeriodEnum'];
  ProtocolActivityTypes: NexusGenEnums['ProtocolActivityTypes'];
  QuestionTypeEnum: NexusGenEnums['QuestionTypeEnum'];
  TitleEnum: NexusGenEnums['TitleEnum'];
}

export interface NexusGenFieldTypes {
  AddNewChapterPayload: { // field return type
    chapter: NexusGenRootTypes['Chapter']; // Chapter!
  }
  AddNewTextPayload: { // field return type
    text: NexusGenRootTypes['Text']; // Text!
  }
  AddStudentsToCoursePayload: { // field return type
    course: NexusGenRootTypes['Course']; // Course!
  }
  AddVocabWordPayload: { // field return type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  AssignEssayPayload: { // field return type
    essay: NexusGenRootTypes['Essay'][]; // [Essay!]!
  }
  Chapter: { // field return type
    _id: string | null; // ID
    chapterNumber: number; // Int!
    chapterTitle: string; // String!
    fromText: NexusGenRootTypes['Text']; // Text!
    hasSections: NexusGenRootTypes['TextSection']; // TextSection!
  }
  Course: { // field return type
    _id: string | null; // ID
    hasStudents: NexusGenRootTypes['Student'][]; // [Student!]!
    hasTeacher: NexusGenRootTypes['Teacher']; // Teacher!
    period: string; // String!
  }
  CreateCoursePayload: { // field return type
    course: NexusGenRootTypes['Course']; // Course!
  }
  CreateTextSectionPayload: { // field return type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  Essay: { // field return type
    _id: string | null; // ID
    assignedDate: any; // Date!
    dueDate: any; // Date!
    exempt: boolean; // Boolean!
    finalDraft: NexusGenRootTypes['FinalDraftContainer'] | null; // FinalDraftContainer
    hasAssigner: NexusGenRootTypes['Teacher']; // Teacher!
    hasOwner: NexusGenRootTypes['Student']; // Student!
    late: boolean; // Boolean!
    markingPeriod: string; // String!
    readings: NexusGenRootTypes['Readings']; // Readings!
    score: NexusGenRootTypes['Score']; // Score!
    topic: NexusGenRootTypes['Topic']; // Topic!
    workingDraft: NexusGenRootTypes['WorkingDraft']; // WorkingDraft!
  }
  FinalDraftContainer: { // field return type
    returned: boolean; // Boolean!
    submitted: boolean; // Boolean!
    submittedFinalDraft: NexusGenRootTypes['SubmittedFinalDraft']; // SubmittedFinalDraft!
    submitTime: any | null; // DateTime
  }
  FindAssignmentsToGradePayload: { // field return type
    assignments: NexusGenRootTypes['Assignment'][]; // [Assignment!]!
  }
  FindChapterTitlePayload: { // field return type
    chapter: NexusGenRootTypes['Chapter']; // Chapter!
  }
  FindChaptersInTextPayload: { // field return type
    chapters: NexusGenRootTypes['Chapter'][]; // [Chapter!]!
  }
  FindEssayByIdPayload: { // field return type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  FindEssaysByUserNameAndMarkingPeriodPayload: { // field return type
    essay: NexusGenRootTypes['Essay'][] | null; // [Essay!]
  }
  FindTextByTitlePayload: { // field return type
    text: NexusGenRootTypes['Text']; // Text!
  }
  FindTextSectionByIdPayload: { // field return type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  FindTextSectionsByChapterPayload: { // field return type
    textSections: NexusGenRootTypes['TextSection'][]; // [TextSection!]!
  }
  FindTextsPayload: { // field return type
    texts: NexusGenRootTypes['Text'][]; // [Text!]!
  }
  LoginPayload: { // field return type
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    addNewChapter: NexusGenRootTypes['AddNewChapterPayload']; // AddNewChapterPayload!
    addNewText: NexusGenRootTypes['AddNewTextPayload']; // AddNewTextPayload!
    addStudentsToCourse: NexusGenRootTypes['AddStudentsToCoursePayload']; // AddStudentsToCoursePayload!
    addVocabWord: NexusGenRootTypes['AddVocabWordPayload']; // AddVocabWordPayload!
    assignEssay: NexusGenRootTypes['AssignEssayPayload']; // AssignEssayPayload!
    changeVocabWord: NexusGenRootTypes['UpdateVocabPayload']; // UpdateVocabPayload!
    createCourse: NexusGenRootTypes['CreateCoursePayload']; // CreateCoursePayload!
    createTextSection: NexusGenRootTypes['CreateTextSectionPayload']; // CreateTextSectionPayload!
    login: NexusGenRootTypes['LoginPayload']; // LoginPayload!
    logout: boolean; // Boolean!
    removeTextSection: NexusGenRootTypes['RemoveTextSectionPayload']; // RemoveTextSectionPayload!
    returnGradedEssay: NexusGenRootTypes['ReturnGradedEssayPayload']; // ReturnGradedEssayPayload!
    studentRegistration: NexusGenRootTypes['StudentRegistrationPayload']; // StudentRegistrationPayload!
    submitEssayFinalDraft: NexusGenRootTypes['SubmitEssayFinalDraftPayload']; // SubmitEssayFinalDraftPayload!
    teacherRegistration: NexusGenRootTypes['TeacherRegistrationPayload']; // TeacherRegistrationPayload!
    updateTextSection: NexusGenRootTypes['UpdateTextSectionPayload']; // UpdateTextSectionPayload!
    updateWorkingDraft: NexusGenRootTypes['UpdateWorkingDraftPayload']; // UpdateWorkingDraftPayload!
  }
  PageNumbers: { // field return type
    endingPage: number; // Int!
    startingPage: number; // Int!
  }
  Query: { // field return type
    findAssignmentsToGrade: NexusGenRootTypes['FindAssignmentsToGradePayload']; // FindAssignmentsToGradePayload!
    findChaptersInText: NexusGenRootTypes['FindChaptersInTextPayload']; // FindChaptersInTextPayload!
    findChapterTitle: NexusGenRootTypes['FindChapterTitlePayload']; // FindChapterTitlePayload!
    findEssayById: NexusGenRootTypes['FindEssayByIdPayload']; // FindEssayByIdPayload!
    findEssaysByUserNameAndMarkingPeriod: NexusGenRootTypes['FindEssaysByUserNameAndMarkingPeriodPayload']; // FindEssaysByUserNameAndMarkingPeriodPayload!
    findTextByTitle: NexusGenRootTypes['FindTextByTitlePayload']; // FindTextByTitlePayload!
    findTexts: NexusGenRootTypes['FindTextsPayload']; // FindTextsPayload!
    findTextSectionById: NexusGenRootTypes['FindTextSectionByIdPayload']; // FindTextSectionByIdPayload!
    findTextSectionsByChapter: NexusGenRootTypes['FindTextSectionsByChapterPayload']; // FindTextSectionsByChapterPayload!
    me: NexusGenRootTypes['User'] | null; // User
  }
  Reading_Guide: { // field return type
    _id: string | null; // ID
    assignedDate: any; // Date!
    completion: string; // String!
    dueDate: any; // Date!
    exempt: boolean; // Boolean!
    hasAssigner: NexusGenRootTypes['Teacher']; // Teacher!
    hasOwner: NexusGenRootTypes['Student']; // Student!
    late: boolean; // Boolean!
    markingPeriod: string; // String!
    readings: NexusGenRootTypes['Readings']; // Readings!
    score: NexusGenRootTypes['Score']; // Score!
  }
  Readings: { // field return type
    readingPages: string; // String!
    readingSections: string; // String!
  }
  RemoveTextSectionPayload: { // field return type
    removed: boolean; // Boolean!
  }
  ReturnGradedEssayPayload: { // field return type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  Score: { // field return type
    earnedPoints: number; // Int!
    maxPoints: number; // Int!
  }
  Student: { // field return type
    _id: string | null; // ID
    email: string | null; // String
    firstName: string; // String!
    hasAssignments: NexusGenRootTypes['Assignment'][]; // [Assignment!]!
    inCourses: NexusGenRootTypes['Course'][]; // [Course!]!
    lastName: string; // String!
    password: string; // String!
    userName: string; // String!
  }
  StudentRegistrationPayload: { // field return type
    student: NexusGenRootTypes['Student']; // Student!
  }
  SubmitEssayFinalDraftPayload: { // field return type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  SubmittedFinalDraft: { // field return type
    comments: string[]; // [String!]!
    draft: any; // JSON!
    gradingDraft: any; // JSON!
    score: number; // Int!
  }
  Teacher: { // field return type
    _id: string | null; // ID
    email: string | null; // String
    firstName: string; // String!
    hasCourses: NexusGenRootTypes['Course'][]; // [Course!]!
    lastName: string; // String!
    password: string; // String!
    title: NexusGenEnums['TitleEnum']; // TitleEnum!
    userName: string; // String!
  }
  TeacherRegistrationPayload: { // field return type
    teacher: NexusGenRootTypes['Teacher']; // Teacher!
  }
  Test: { // field return type
    _id: string | null; // ID
    assignedDate: any; // Date!
    dueDate: any; // Date!
    exempt: boolean; // Boolean!
    hasAssigner: NexusGenRootTypes['Teacher']; // Teacher!
    hasOwner: NexusGenRootTypes['Student']; // Student!
    late: boolean; // Boolean!
    markingPeriod: string; // String!
    readings: NexusGenRootTypes['Readings']; // Readings!
    score: NexusGenRootTypes['Score']; // Score!
    testName: string; // String!
  }
  Text: { // field return type
    _id: string | null; // ID
    hasChapters: NexusGenRootTypes['Chapter'][]; // [Chapter!]!
    textTitle: string; // String!
  }
  TextSection: { // field return type
    _id: string | null; // ID
    fromChapter: NexusGenRootTypes['Chapter']; // Chapter!
    hasProtocols: NexusGenRootTypes['TextSectionProtocols'][]; // [TextSectionProtocols!]!
    hasQuestions: NexusGenRootTypes['TextSectionQuestions'][]; // [TextSectionQuestions!]!
    hasVocab: NexusGenRootTypes['TextSectionVocab'][]; // [TextSectionVocab!]!
    header: string; // String!
    pageNumbers: NexusGenRootTypes['PageNumbers']; // PageNumbers!
  }
  TextSectionProtocols: { // field return type
    academicOutcomeTypes: NexusGenEnums['AcademicOutomeTypes']; // AcademicOutomeTypes!
    activityType: NexusGenEnums['ProtocolActivityTypes']; // ProtocolActivityTypes!
    task: string; // String!
  }
  TextSectionQuestions: { // field return type
    question: string; // String!
    questionType: NexusGenEnums['QuestionTypeEnum']; // QuestionTypeEnum!
  }
  TextSectionVocab: { // field return type
    definition: string; // String!
    word: string; // String!
  }
  Topic: { // field return type
    question: string; // String!
    questionType: NexusGenEnums['QuestionTypeEnum']; // QuestionTypeEnum!
  }
  UpdateTextSectionPayload: { // field return type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  UpdateVocabPayload: { // field return type
    textSection: NexusGenRootTypes['TextSection']; // TextSection!
  }
  UpdateWorkingDraftPayload: { // field return type
    essay: NexusGenRootTypes['Essay']; // Essay!
  }
  WorkingDraft: { // field return type
    draft: any; // JSON!
  }
  Assignment: { // field return type
    _id: string | null; // ID
    assignedDate: any; // Date!
    dueDate: any; // Date!
    exempt: boolean; // Boolean!
    hasAssigner: NexusGenRootTypes['Teacher']; // Teacher!
    hasOwner: NexusGenRootTypes['Student']; // Student!
    late: boolean; // Boolean!
    markingPeriod: string; // String!
    readings: NexusGenRootTypes['Readings']; // Readings!
    score: NexusGenRootTypes['Score']; // Score!
  }
  User: { // field return type
    _id: string | null; // ID
    email: string | null; // String
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
    userName: string; // String!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addNewChapter: { // args
      input: NexusGenInputs['AddNewChapterInput']; // AddNewChapterInput!
    }
    addNewText: { // args
      input: NexusGenInputs['AddNewTextInput']; // AddNewTextInput!
    }
    addStudentsToCourse: { // args
      input: NexusGenInputs['AddStudentsToCourseInput']; // AddStudentsToCourseInput!
    }
    addVocabWord: { // args
      input: NexusGenInputs['AddVocabWordInput']; // AddVocabWordInput!
    }
    assignEssay: { // args
      input: NexusGenInputs['AssignEssayInput']; // AssignEssayInput!
    }
    changeVocabWord: { // args
      input: NexusGenInputs['ChangeVocabWordInput']; // ChangeVocabWordInput!
    }
    createCourse: { // args
      input: NexusGenInputs['CreateCourseInput']; // CreateCourseInput!
    }
    createTextSection: { // args
      input: NexusGenInputs['CreateTextSectionInput']; // CreateTextSectionInput!
    }
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    removeTextSection: { // args
      input: NexusGenInputs['RemoveTextSectionInput']; // RemoveTextSectionInput!
    }
    returnGradedEssay: { // args
      input: NexusGenInputs['ReturnGradedEssayInput']; // ReturnGradedEssayInput!
    }
    studentRegistration: { // args
      input: NexusGenInputs['StudentRegistrationInput']; // StudentRegistrationInput!
    }
    submitEssayFinalDraft: { // args
      input: NexusGenInputs['SubmitEssayFinalDraftInput']; // SubmitEssayFinalDraftInput!
    }
    teacherRegistration: { // args
      input: NexusGenInputs['TeacherRegistrationInput']; // TeacherRegistrationInput!
    }
    updateTextSection: { // args
      input: NexusGenInputs['UpdateTextSectionInput']; // UpdateTextSectionInput!
    }
    updateWorkingDraft: { // args
      input: NexusGenInputs['UpdateWorkingDraftInput']; // UpdateWorkingDraftInput!
    }
  }
  Query: {
    findAssignmentsToGrade: { // args
      input: NexusGenInputs['FindAssignmentsToGradeInput']; // FindAssignmentsToGradeInput!
    }
    findChaptersInText: { // args
      input: NexusGenInputs['FindChaptersInTextInput']; // FindChaptersInTextInput!
    }
    findChapterTitle: { // args
      input: NexusGenInputs['FindChapterTitleInput']; // FindChapterTitleInput!
    }
    findEssayById: { // args
      input: NexusGenInputs['FindEssayByIdInput']; // FindEssayByIdInput!
    }
    findEssaysByUserNameAndMarkingPeriod: { // args
      input: NexusGenInputs['FindEssaysByUserNameAndMarkingPeriodInput']; // FindEssaysByUserNameAndMarkingPeriodInput!
    }
    findTextByTitle: { // args
      input: NexusGenInputs['FindTextByTitleInput']; // FindTextByTitleInput!
    }
    findTextSectionById: { // args
      input: NexusGenInputs['FindTextSectionByIdInput']; // FindTextSectionByIdInput!
    }
    findTextSectionsByChapter: { // args
      input: NexusGenInputs['FindTextSectionsByChapterInput']; // FindTextSectionsByChapterInput!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
  Assignment: "Essay" | "Reading_Guide" | "Test"
  User: "Student" | "Teacher"
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "AddNewChapterPayload" | "AddNewTextPayload" | "AddStudentsToCoursePayload" | "AddVocabWordPayload" | "AssignEssayPayload" | "Chapter" | "Course" | "CreateCoursePayload" | "CreateTextSectionPayload" | "Essay" | "FinalDraftContainer" | "FindAssignmentsToGradePayload" | "FindChapterTitlePayload" | "FindChaptersInTextPayload" | "FindEssayByIdPayload" | "FindEssaysByUserNameAndMarkingPeriodPayload" | "FindTextByTitlePayload" | "FindTextSectionByIdPayload" | "FindTextSectionsByChapterPayload" | "FindTextsPayload" | "LoginPayload" | "Mutation" | "PageNumbers" | "Query" | "Reading_Guide" | "Readings" | "RemoveTextSectionPayload" | "ReturnGradedEssayPayload" | "Score" | "Student" | "StudentRegistrationPayload" | "SubmitEssayFinalDraftPayload" | "SubmittedFinalDraft" | "Teacher" | "TeacherRegistrationPayload" | "Test" | "Text" | "TextSection" | "TextSectionProtocols" | "TextSectionQuestions" | "TextSectionVocab" | "Topic" | "UpdateTextSectionPayload" | "UpdateVocabPayload" | "UpdateWorkingDraftPayload" | "WorkingDraft";

export type NexusGenInputNames = "AddNewChapterInput" | "AddNewTextInput" | "AddStudentsToCourseInput" | "AddVocabWordInput" | "AssignEssayInput" | "ChangeVocabWordInput" | "CreateCourseInput" | "CreateTextSectionInput" | "FindAssignmentsToGradeInput" | "FindChapterTitleInput" | "FindChaptersInTextInput" | "FindEssayByIdInput" | "FindEssaysByUserNameAndMarkingPeriodInput" | "FindTextByTitleInput" | "FindTextSectionByIdInput" | "FindTextSectionsByChapterInput" | "HasAssigner" | "HasOwnerInput" | "LoginInput" | "PageNumbersInput" | "ReadingsInput" | "RemoveTextSectionInput" | "ReturnGradedEssayInput" | "StudentRegistrationInput" | "SubmitEssayFinalDraftInput" | "SubmittedFinalDraftsInput" | "TeacherRegistrationInput" | "TextChapterInput" | "TextInput" | "TextSectionProtocolsInput" | "TextSectionQuestionsInput" | "TextSectionVocabInput" | "TopicInput" | "UpdateTextSectionInput" | "UpdateWorkingDraftInput";

export type NexusGenEnumNames = "AcademicOutomeTypes" | "MarkingPeriodEnum" | "ProtocolActivityTypes" | "QuestionTypeEnum" | "TitleEnum";

export type NexusGenInterfaceNames = "Assignment" | "User";

export type NexusGenScalarNames = "Boolean" | "Date" | "DateTime" | "Float" | "ID" | "Int" | "JSON" | "String" | "Time";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: t.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}